#!/usr/bin/env node
/**
 * Starlight Reverie — build tool
 *
 * Assembles the modular ExtendScript source tree into a single deliverable,
 * dist/FINAL_PROJECT.jsx, by concatenating the modules listed in build/manifest.json
 * (in order), stripping stray ExtendScript directives, wrapping in the AE target +
 * an outer guard that cleans the global namespace after the run, and optionally
 * running a syntax check.
 *
 * Usage:
 *   node tools/build.js                 -> writes dist/FINAL_PROJECT.jsx
 *   node tools/build.js out.jsx         -> writes a custom output path
 *   node tools/build.js --check         -> assemble to a temp file, run `node --check`, do not write dist
 *
 * ES5/Node only. No external dependencies.
 */
"use strict";

var fs = require("fs");
var path = require("path");
var cp = require("child_process");

var PROJECT_ROOT = path.join(__dirname, "..");
var MANIFEST = path.join(PROJECT_ROOT, "build", "manifest.json");

function readManifest() {
    if (!fs.existsSync(MANIFEST)) {
        throw new Error("manifest not found: " + MANIFEST);
    }
    return JSON.parse(fs.readFileSync(MANIFEST, "utf8"));
}

// Remove ExtendScript preprocessor directives that must not appear inside modules
// (the build tool owns target + ordering). Leaves normal code untouched.
function stripDirectives(src) {
    return src
        .split("\n")
        .filter(function (line) {
            var t = line.replace(/^﻿/, "").trim();
            return !(/^#target\b/.test(t) || /^#include\b/.test(t) || /^\/\/@include\b/.test(t) || /^#targetengine\b/.test(t));
        })
        .join("\n");
}

function banner(manifest) {
    return [
        "// =====================================================================================",
        "//  " + manifest.name + " — FINAL_PROJECT.jsx  (generated by tools/build.js — do not edit)",
        "//  Version " + manifest.version + "  |  Target: " + manifest.target,
        "//  Assembled from " + manifest.modules.length + " modules in build/manifest.json order.",
        "//  Source of truth: production-bible/PRODUCTION-BIBLE.md",
        "//  Generated: " + new Date().toISOString(),
        "// =====================================================================================",
        ""
    ].join("\n");
}

function assemble(manifest) {
    var parts = [];
    parts.push(banner(manifest));
    parts.push("#target aftereffects");
    parts.push("(function () {");
    parts.push('    "use strict";');
    parts.push("    // ---- modules (concatenated in manifest order) ----");
    manifest.modules.forEach(function (rel) {
        var abs = path.join(PROJECT_ROOT, rel);
        if (!fs.existsSync(abs)) {
            throw new Error("module listed in manifest not found: " + rel);
        }
        var src = stripDirectives(fs.readFileSync(abs, "utf8"));
        parts.push("");
        parts.push("    // ===== " + rel + " =====");
        parts.push(src);
    });
    parts.push("");
    parts.push("    // ---- entry ----");
    parts.push("    // The 'main' entry module (added to the manifest at packaging, Stage 21) calls SR.build().");
    parts.push("    try { if (typeof $ !== 'undefined' && $.global && typeof $.global.SR !== 'undefined' && $.global.SR.build) { $.global.SR.build(); } } catch (e) { try { alert('Starlight Reverie build error: ' + e.toString()); } catch (e2) {} }");
    parts.push("    // ---- namespace cleanup so repeated runs start clean ----");
    parts.push("    try { if (typeof $ !== 'undefined' && $.global) { delete $.global.SR; } } catch (e) {}");
    parts.push("})();");
    parts.push("");
    return parts.join("\n");
}

function main() {
    var args = process.argv.slice(2);
    var checkOnly = args.indexOf("--check") !== -1;
    var outArg = args.filter(function (a) { return a.indexOf("--") !== 0; })[0];

    var manifest = readManifest();
    var code = assemble(manifest);

    var outPath;
    if (checkOnly) {
        outPath = path.join(require("os").tmpdir(), "SR_build_check_" + Date.now() + ".js");
    } else {
        outPath = outArg ? path.resolve(outArg) : path.join(PROJECT_ROOT, manifest.output);
        var outDir = path.dirname(outPath);
        if (!fs.existsSync(outDir)) { fs.mkdirSync(outDir, { recursive: true }); }
    }

    fs.writeFileSync(outPath, code, "utf8");

    // Syntax check (strip the ExtendScript #target line, which Node cannot parse).
    var checkFile = path.join(require("os").tmpdir(), "SR_syntax_" + Date.now() + ".js");
    fs.writeFileSync(checkFile, code.replace(/^#target.*$/m, "// (#target stripped for node --check)"), "utf8");
    try {
        cp.execSync("node --check " + JSON.stringify(checkFile), { stdio: "pipe" });
        console.log("[build] syntax OK  (" + manifest.modules.length + " modules, " + code.split("\n").length + " lines)");
    } catch (e) {
        console.error("[build] SYNTAX ERROR:\n" + (e.stderr ? e.stderr.toString() : e.toString()));
        process.exitCode = 1;
    } finally {
        try { fs.unlinkSync(checkFile); } catch (e) {}
    }

    if (checkOnly) {
        try { fs.unlinkSync(outPath); } catch (e) {}
        console.log("[build] --check only: no dist written.");
    } else {
        console.log("[build] wrote " + path.relative(PROJECT_ROOT, outPath));
    }
}

main();
